//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTag.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class myLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal myLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyTag.Properties.Langs.myLang", typeof(myLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tag.
        /// </summary>
        public static string BT_AddNewTag {
            get {
                return ResourceManager.GetString("BT_AddNewTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Tag.
        /// </summary>
        public static string BT_DeleteTag {
            get {
                return ResourceManager.GetString("BT_DeleteTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite Tags.
        /// </summary>
        public static string BT_FavouriteTags {
            get {
                return ResourceManager.GetString("BT_FavouriteTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Image.
        /// </summary>
        public static string BT_ImportImages {
            get {
                return ResourceManager.GetString("BT_ImportImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Tag.
        /// </summary>
        public static string BT_ModifyTag {
            get {
                return ResourceManager.GetString("BT_ModifyTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Images.
        /// </summary>
        public static string BT_RecentImages {
            get {
                return ResourceManager.GetString("BT_RecentImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string BT_Settings {
            get {
                return ResourceManager.GetString("BT_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Tags.
        /// </summary>
        public static string BT_ShowMyTags {
            get {
                return ResourceManager.GetString("BT_ShowMyTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string CM_CopyImageCB {
            get {
                return ResourceManager.GetString("CM_CopyImageCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy path.
        /// </summary>
        public static string CM_CopyPath {
            get {
                return ResourceManager.GetString("CM_CopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string CM_Delete {
            get {
                return ResourceManager.GetString("CM_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify tags.
        /// </summary>
        public static string CM_ModifyTags {
            get {
                return ResourceManager.GetString("CM_ModifyTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string CM_Open {
            get {
                return ResourceManager.GetString("CM_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open location.
        /// </summary>
        public static string CM_OpenLocation {
            get {
                return ResourceManager.GetString("CM_OpenLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string CM_Rename {
            get {
                return ResourceManager.GetString("CM_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        public static string CM_Rotate {
            get {
                return ResourceManager.GetString("CM_Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save on desktop.
        /// </summary>
        public static string CM_SaveOnDesktop {
            get {
                return ResourceManager.GetString("CM_SaveOnDesktop", resourceCulture);
            }
        }
    }
}
